language: node_js
sudo: false
env:
  global:
    - secure: fyHOH0NftlAdy2tQawAq+qqcnc7GWo7ojRl5oHi30ueu79wFWTTWWvARCA8eo+FtWZsGlLfvyuzpmjnbJfMaN3wCzVfCG8ddd+nDhYKYbA4j+iqJarELQlVY5QguVGryO1emRPxFg2+WaSiaHCEvp5/eC7KYyHmlGtq0K0y1Svc=
    - secure: y/hyg7hEbYMoBjQOJ8UUrRp01PT4un0fTJWzNbRWUzAC6RXNOPd/SaOREHkJ/exLoyl5xV5I3gI4jOqy/KgtOH1DBEDuV6puq61Xc5C5GQ7OWiTNAnUZIbmNeTNgKdsfOySLvrEMNVN5xfL/SPe9yQKB2R4fUZ1MdBDAHs+xIas=

script: grunt travis

matrix:
  include:
    - node_js: "0.10"
      env: KARMA=false
    - node_js: "node"
      env: KARMA=
    - node_js: "iojs"
      env: KARMA=false

cache:
  directories:
    - node_modules
