os:
  - linux
  - osx
osx_image: xcode7.3
sudo: required
language: node_js
node_js:
  - "6.2.2"
  - "10"
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glib ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pixman ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash install-dependencies.sh ; fi
script:
  - npm install --ignore-scripts
  - npm run build
